N = 256;
x_min = -5;
x_max = 5;
x = linspace(x_min, x_max, N);
f = exp(-x.^2);
F = fft(f);
F_shifted = fftshift(F);
dx = x(2) - x(1);
freq = (-N/2:N/2-1) / (N*dx);
subplot(2,1,1);
plot(x, f);
title("f(x) = e^{-x^2}");
xlabel("x");
ylabel("f(x)");
subplot(2,1,2);
plot(freq, abs(F_shifted));
title("Magnitude of FFT of e^{-x^2}");
xlabel("Frequency");
ylabel("|F(w)|");
